package org.neo4j.tutorial;

import static org.neo4j.tutorial.PlanetBuilder.planet;

import org.neo4j.graphdb.Transaction;

public class Planets {

    private final DoctorWhoUniverse universe;

    public Planets(DoctorWhoUniverse universe) {
        this.universe = universe;
    }

    public void insert() {
        Transaction tx = universe.getDatabase().beginTx();
        try {
            planet("4-X-Alpha-4").fact(universe);
            planet("Abydos").fact(universe);
            planet("Adipose 3").fact(universe);
            planet("Agora").fact(universe);
            planet("Alfava Metraxis").fact(universe);
            planet("Algol").fact(universe);
            planet("Alpha Canis One").fact(universe);
            planet("Althrace").fact(universe);
            planet("Alvega").fact(universe);
            planet("Alzarius").fact(universe);
            planet("Amanopia").fact(universe);
            planet("Anagonia").fact(universe);
            planet("Anathema").fact(universe);
            planet("Androzani Major").fact(universe);
            planet("Aneth").fact(universe);
            planet("Anima Persis").fact(universe);
            planet("Anura").fact(universe);
            planet("Aractus").fact(universe);
            planet("Arcadia").fact(universe);
            planet("Arcateen V").fact(universe);
            planet("Archetryx").fact(universe);
            planet("Arden").fact(universe);
            planet("Argolis").fact(universe);
            planet("Argos").fact(universe);
            planet("Aridius").fact(universe);
            planet("Arkannis Major").fact(universe);
            planet("Arkheon").fact(universe);
            planet("Artaris").fact(universe);
            planet("Asgard").fact(universe);
            planet("Astra").fact(universe);
            planet("Atrios").fact(universe);
            planet("Augea ").fact(universe);
            planet("Auros").fact(universe);
            planet("Avalon").fact(universe);
            planet("Axista Four").fact(universe);
            planet("Azure").fact(universe);
            planet("Balhoon").fact(universe);
            planet("Bandraginus 5").fact(universe);
            planet("Bandril").fact(universe);
            planet("Bane World").fact(universe);
            planet("Barcelona").fact(universe);
            planet("Bel").fact(universe);
            planet("Belannia II").fact(universe);
            planet("Belannia IV").fact(universe);
            planet("Belepheron").fact(universe);
            planet("Bellaphores").fact(universe);
            planet("Bessan").fact(universe);
            planet("Beta Two").fact(universe);
            planet("Betelgeuse").fact(universe);
            planet("Betrushia").fact(universe);
            planet("Bi").fact(universe);
            planet("Blenhorm Ogin").fact(universe);
            planet("Blestinu").fact(universe);
            planet("Blini-Gaar").fact(universe);
            planet("Bliss").fact(universe);
            planet("Bonarcha Anarda").fact(universe);
            planet("Boromeo").fact(universe);
            planet("Bortresoye").fact(universe);
            planet("Bruydac").fact(universe);
            planet("Brus").fact(universe);
            planet("Bouken").fact(universe);
            planet("Calliopticon").fact(universe);
            planet("Calufrax").fact(universe);
            planet("Calufrax Minor").fact(universe);
            planet("Carsus").fact(universe);
            planet("Cassius").fact(universe);
            planet("Castor 36").fact(universe);
            planet("Castrovalva").fact(universe);
            planet("Catastrophea").fact(universe);
            planet("Catrigan Nova").fact(universe);
            planet("Centauri Seven").fact(universe);
            planet("Cep Cassalon").fact(universe);
            planet("Chavic Five").fact(universe);
            planet("Cheem").fact(universe);
            planet("Cheetah Planet").fact(universe);
            planet("Chelonia").fact(universe);
            planet("Chimeria").fact(universe);
            planet("Chimera IV").fact(universe);
            planet("Chloris").fact(universe);
            planet("Chronos").fact(universe);
            planet("Cinethon").fact(universe);
            planet("Clom").fact(universe);
            planet("Colano Alpha").fact(universe);
            planet("Collactin").fact(universe);
            planet("Cotter Palluni's World").fact(universe);
            planet("Crafe Tec Heydra").fact(universe);
            planet("Crespallion").fact(universe);
            planet("Crestus").fact(universe);
            planet("Crinoth").fact(universe);
            planet("Cyrennis Minima").fact(universe);
            planet("Daemos").fact(universe);
            planet("Dar").fact(universe);
            planet("Darkheart").fact(universe);
            planet("Darp").fact(universe);
            planet("Darillium").fact(universe);
            planet("Delphon").fact(universe);
            planet("Delta Magna'").fact(universe);
            planet("Desperus").fact(universe);
            planet("Deva Loka").fact(universe);
            planet("Dhakan").fact(universe);
            planet("Diadem").fact(universe);
            planet("Dido").fact(universe);
            planet("Dioscuros").fact(universe);
            planet("Diplos").fact(universe);
            planet("Discurus").fact(universe);
            planet("Draconia").fact(universe);
            planet("Dramos").fact(universe);
            planet("Drahva").fact(universe);
            planet("Dravidia").fact(universe);
            planet("Dronid").fact(universe);
            planet("Duchamp 331").fact(universe);
            planet("Dulkis").fact(universe);
            planet("Earth").fact(universe);
            planet("Eden").fact(universe);
            planet("Ephte Major").fact(universe);
            planet("Enlandia").fact(universe);
            planet("Epsilon Four Zero Gamma").fact(universe);
            planet("Esto").fact(universe);
            planet("Eudamus").fact(universe);
            planet("Exarius").fact(universe);
            planet("Exxilon").fact(universe);
            planet("Eye of Orion").fact(universe);
            planet("Fagiros").fact(universe);
            planet("Felspoon").fact(universe);
            planet("The Fifth Planet").fact(universe);
            planet("Fisar").fact(universe);
            planet("Flane").fact(universe);
            planet("Florana").fact(universe);
            planet("Freytus").fact(universe);
            planet("Frontios").fact(universe);
            planet("Galaxis Bright").fact(universe);
            planet("Gallifrey").fact(universe);
            planet("Galsec Seven").fact(universe);
            planet("Gameworld Gamma").fact(universe);
            planet("Gauda Prime").fact(universe);
            planet("Gidu").fact(universe);
            planet("Glasson Minor").fact(universe);
            planet("Golo").fact(universe);
            planet("Gond Homeworld").fact(universe);
            planet("Gotta Floco").fact(universe);
            planet("Grajick Major").fact(universe);
            planet("Granados").fact(universe);
            planet("Gratt").fact(universe);
            planet("Griffoth").fact(universe);
            planet("Griophos").fact(universe);
            planet("Grold Homeworld").fact(universe);
            planet("Grolon").fact(universe);
            planet("Grundle").fact(universe);
            planet("Hakol (aka. Harkol)").fact(universe);
            planet("Halcya").fact(universe);
            planet("Halergan Three").fact(universe);
            planet("Hastus Minor").fact(universe);
            planet("Heaven").fact(universe);
            planet("Hedron").fact(universe);
            planet("Heiradi").fact(universe);
            planet("Hell").fact(universe);
            planet("Hermethica").fact(universe);
            planet("Hurala").fact(universe);
            planet("Hyspero").fact(universe);
            planet("Hydropellica Hydroxi").fact(universe);
            planet("Indigo 3").fact(universe);
            planet("Inter Minor").fact(universe);
            planet("Iphitus").fact(universe);
            planet("Jaconda").fact(universe);
            planet("Jahoo").fact(universe);
            planet("Jalian 17").fact(universe);
            planet("Jan Francis IX").fact(universe);
            planet("Junk").fact(universe);
            planet("Jupiter").fact(universe);
            planet("Justicia").fact(universe);
            planet("Kalakiki").fact(universe);
            planet("Kalaya").fact(universe);
            planet("Kaldor").fact(universe);
            planet("Kantra").fact(universe);
            planet("Kanval").fact(universe);
            planet("Kapteyn 5").fact(universe);
            planet("Kar-Charrat").fact(universe);
            planet("Karfel").fact(universe);
            planet("Karn").fact(universe);
            planet("Karas don Kazra don Slava").fact(universe);
            planet("Karris").fact(universe);
            planet("Kas").fact(universe);
            planet("Kastopheria").fact(universe);
            planet("Kastria").fact(universe);
            planet("Katakiki").fact(universe);
            planet("Katuria").fact(universe);
            planet("Kegron Pluva").fact(universe);
            planet("Kem").fact(universe);
            planet("Kinjana").fact(universe);
            planet("Kirith").fact(universe);
            planet("Klechton").fact(universe);
            planet("Kolkokron").fact(universe);
            planet("Kosnax").fact(universe);
            planet("Kreme").fact(universe);
            planet("Krillia").fact(universe);
            planet("Krontep").fact(universe);
            planet("Krop Tor").fact(universe);
            planet("Kurhan").fact(universe);
            planet("Kylos").fact(universe);
            planet("Kyrol").fact(universe);
            planet("Lakertya").fact(universe);
            planet("Laylora").fact(universe);
            planet("Leela's World").fact(universe);
            planet("Lelex").fact(universe);
            planet("Leophantos").fact(universe);
            planet("Levithia").fact(universe);
            planet("The Li").fact(universe);
            planet("Limus 4").fact(universe);
            planet("Livonia").fact(universe);
            planet("Loam").fact(universe);
            planet("Lo").fact(universe);
            planet("Logopolis").fact(universe);
            planet("Lonsis").fact(universe);
            planet("Lowitelom").fact(universe);
            planet("Lucifer").fact(universe);
            planet("Lurma").fact(universe);
            planet("Lvan (aka. Luan)").fact(universe);
            planet("Magellan").fact(universe);
            planet("Magla").fact(universe);
            planet("Magnus").fact(universe);
            planet("Malcassairo").fact(universe);
            planet("Manussa").fact(universe);
            planet("Marinus").fact(universe);
            planet("Marpesia").fact(universe);
            planet("Mars").fact(universe);
            planet("Mechanus").fact(universe);
            planet("Melagophon").fact(universe);
            planet("Melissa Majoria").fact(universe);
            planet("Mer").fact(universe);
            planet("Mesmerus").fact(universe);
            planet("Messaline").fact(universe);
            planet("Metallurgis 5").fact(universe);
            planet("Meta Sigmafolio").fact(universe);
            planet("Meta Vorka 6").fact(universe);
            planet("Mete").fact(universe);
            planet("Metralu").fact(universe);
            planet("Miasimia Goria").fact(universe);
            planet("Midnight").fact(universe);
            planet("Minyos").fact(universe);
            planet("Mira").fact(universe);
            planet("Mira").fact(universe);
            planet("Mo").fact(universe);
            planet("Mogar").fact(universe);
            planet("Mondaran").fact(universe);
            planet("Mondas").fact(universe);
            planet("Morestra").fact(universe);
            planet("Morok").fact(universe);
            planet("Museum of the Last Ones").fact(universe);
            planet("Muscolane").fact(universe);
            planet("Myarr").fact(universe);
            planet("Navaros").fact(universe);
            planet("Necros").fact(universe);
            planet("Nefrin").fact(universe);
            planet("Neogorgon").fact(universe);
            planet("New Alexandria").fact(universe);
            planet("New Earth").fact(universe);
            planet("New Savannah").fact(universe);
            planet("New Venus").fact(universe);
            planet("Nooma").fact(universe);
            planet("Nyrruh 4").fact(universe);
            planet("Oberon").fact(universe);
            planet("Oblivion").fact(universe);
            planet("Ockora").fact(universe);
            planet("Ogros").fact(universe);
            planet("Olympus").fact(universe);
            planet("Omphalos").fact(universe);
            planet("One").fact(universe);
            planet("Oseidon").fact(universe);
            planet("Oskerion").fact(universe);
            planet("Othrys").fact(universe);
            planet("Overod").fact(universe);
            planet("Padrivole Regency 9").fact(universe);
            planet("Pandatorea").fact(universe);
            planet("Parakon").fact(universe);
            planet("Paradost").fact(universe);
            planet("Peladon").fact(universe);
            planet("Pen Haxico 2").fact(universe);
            planet("Peri").fact(universe);
            planet("Phaester Osiris").fact(universe);
            planet("Pheros").fact(universe);
            planet("Phryxus").fact(universe);
            planet("Pictos").fact(universe);
            planet("Planet 1").fact(universe);
            planet("Pluto").fact(universe);
            planet("Polymos").fact(universe);
            planet("Polongus").fact(universe);
            planet("Poosh").fact(universe);
            planet("Ponton").fact(universe);
            planet("Posikar").fact(universe);
            planet("Proamon").fact(universe);
            planet("Proxima Centauri").fact(universe);
            planet("Pyro Shika").fact(universe);
            planet("Pyrovilia").fact(universe);
            planet("Qualactin").fact(universe);
            planet("Quinnis").fact(universe);
            planet("Raaga").fact(universe);
            planet("Rago Rago Five Six Rago").fact(universe);
            planet("Ralafea").fact(universe);
            planet("Ranx").fact(universe);
            planet("Ravolox").fact(universe);
            planet("Raxacoricofallapatorius").fact(universe);
            planet("Re").fact(universe);
            planet("Red Rocket Rising").fact(universe);
            planet("Red Sky Lost").fact(universe);
            planet("Refusis II").fact(universe);
            planet("Reja Magnum").fact(universe);
            planet("Rex Vox Jax").fact(universe);
            planet("Rexel 4").fact(universe);
            planet("Ri").fact(universe);
            planet("Riftan Five").fact(universe);
            planet("Rigel Beta 5").fact(universe);
            planet("Rit").fact(universe);
            planet("Ruta 3").fact(universe);
            planet("Ruta Magnum").fact(universe);
            planet("Ry'leh").fact(universe);
            planet("S14").fact(universe);
            planet("Salarius").fact(universe);
            planet("Salostophus").fact(universe);
            planet("Salvak").fact(universe);
            planet("San Helios").fact(universe);
            planet("San Kaloon").fact(universe);
            planet("Santiny").fact(universe);
            planet("Sant's World").fact(universe);
            planet("Sarn").fact(universe);
            planet("Saturnyne").fact(universe);
            planet("Sava").fact(universe);
            planet("Scalpor").fact(universe);
            planet("Scrantek").fact(universe);
            planet("Scotia").fact(universe);
            planet("Segonax").fact(universe);
            planet("Sense-Sphere").fact(universe);
            planet("Shada").fact(universe);
            planet("Shadmoch").fact(universe);
            planet("Shallacatop").fact(universe);
            planet("Shan Shen").fact(universe);
            planet("Shantella Prime").fact(universe);
            planet("Sigma").fact(universe);
            planet("Siralos").fact(universe);
            planet("Sireen").fact(universe);
            planet("Sirius IV").fact(universe);
            planet("Sirius V").fact(universe);
            planet("Skaar").fact(universe);
            planet("Skaro").fact(universe);
            planet("Skonnos").fact(universe);
            planet("Skythros").fact(universe);
            planet("The Slough").fact(universe);
            planet("Solos").fact(universe);
            planet("Sontar").fact(universe);
            planet("Spiridon").fact(universe);
            planet("Splendurosa").fact(universe);
            planet("Starfall").fact(universe);
            planet("Stella Stora").fact(universe);
            planet("Sto").fact(universe);
            planet("Strepto").fact(universe);
            planet("Stricium").fact(universe);
            planet("Sunday").fact(universe);
            planet("Svartos").fact(universe);
            planet("Sycorax").fact(universe);
            planet("Sylvaniar").fact(universe);
            planet("Sza").fact(universe);
            planet("Ta").fact(universe);
            planet("Tara").fact(universe);
            planet("Tarsius").fact(universe);
            planet("Taurean Nomeworld").fact(universe);
            planet("Telos").fact(universe);
            planet("Tenten 10").fact(universe);
            planet("Terileptus").fact(universe);
            planet("Terra Alpha").fact(universe);
            planet("Terra Beta").fact(universe);
            planet("Terradon").fact(universe);
            planet("Tersurus").fact(universe);
            planet("Tetrapyriar").fact(universe);
            planet("Thegeros").fact(universe);
            planet("Thera").fact(universe);
            planet("Therka").fact(universe);
            planet("Therra").fact(universe);
            planet("Thordon").fact(universe);
            planet("Thoros Alpha").fact(universe);
            planet("Thrace").fact(universe);
            planet("Thuron").fact(universe);
            planet("Tiermann's World").fact(universe);
            planet("Tigella").fact(universe);
            planet("Tigus").fact(universe);
            planet("Tisar").fact(universe);
            planet("Titan").fact(universe);
            planet("Titan 3").fact(universe);
            planet("Titania").fact(universe);
            planet("Tokl").fact(universe);
            planet("Toop").fact(universe);
            planet("Torajii Alpha").fact(universe);
            planet("Traken").fact(universe);
            planet("Trieste").fact(universe);
            planet("Tranquela").fact(universe);
            planet("Trion").fact(universe);
            planet("Triton").fact(universe);
            planet("Tythonus").fact(universe);
            planet("Um").fact(universe);
            planet("Unicepter IV").fact(universe);
            planet("Uranus").fact(universe);
            planet("Ur").fact(universe);
            planet("Usurius").fact(universe);
            planet("Utopia").fact(universe);
            planet("UX-4732").fact(universe);
            planet("Uxarieus").fact(universe);
            planet("Vampire Planet").fact(universe);
            planet("Vandos").fact(universe);
            planet("Varos").fact(universe);
            planet("Vardon").fact(universe);
            planet("Varnicon").fact(universe);
            planet("Vasilip").fact(universe);
            planet("Vel Consadine").fact(universe);
            planet("Venessia").fact(universe);
            planet("Venus").fact(universe);
            planet("Verd").fact(universe);
            planet("Verticulus").fact(universe);
            planet("Veturia").fact(universe);
            planet("Vij").fact(universe);
            planet("Viperon").fact(universe);
            planet("Vita 15").fact(universe);
            planet("Voga").fact(universe);
            planet("Volag-Noc").fact(universe);
            planet("Vollotha").fact(universe);
            planet("Voracia").fact(universe);
            planet("Vortis").fact(universe);
            planet("Vulcan").fact(universe);
            planet("Vulpana").fact(universe);
            planet("Wilson 1").fact(universe);
            planet("Woldyhool").fact(universe);
            planet("Woman Wept").fact(universe);
            planet("Xenon").fact(universe);
            planet("Xeros").fact(universe);
            planet("Xeriphas").fact(universe);
            planet("Yegros Alpha").fact(universe);
            planet("Zaakros").fact(universe);
            planet("Zamper").fact(universe);
            planet("Zanak").fact(universe);
            planet("Zazz").fact(universe);
            planet("Zeen 4").fact(universe);
            planet("Zeos").fact(universe);
            planet("Zephon").fact(universe);
            planet("Zeta Major").fact(universe);
            planet("Zeta Minor").fact(universe);
            planet("Zil").fact(universe);
            planet("Zolfa Thura").fact(universe);
            planet("Zom").fact(universe);
            planet("Zygor").fact(universe);

            tx.success();
        } finally {
            tx.finish();
        }
    }
}
