package org.neo4j.tutorial;

import org.neo4j.graphdb.GraphDatabaseService;
import org.neo4j.graphdb.Transaction;

import static org.neo4j.tutorial.PlanetBuilder.planets;

public class Planets
{

    private final GraphDatabaseService db;

    public Planets( GraphDatabaseService db )
    {
        this.db = db;
    }

    public void insert()
    {
        try ( Transaction tx = db.beginTx() )
        {
            planets()
                    .add( "4-X-Alpha-4" )
                    .add( "Abydos" )
                    .add( "Adipose 3" )
                    .add( "Agora" )
                    .add( "Alfava Metraxis" )
                    .add( "Algol" )
                    .add( "Alpha Canis One" )
                    .add( "Althrace" )
                    .add( "Alvega" )
                    .add( "Alzarius" )
                    .add( "Amanopia" )
                    .add( "Anagonia" )
                    .add( "Anathema" )
                    .add( "Androzani Major" )
                    .add( "Aneth" )
                    .add( "Anima Persis" )
                    .add( "Anura" )
                    .add( "Aractus" )
                    .add( "Arcadia" )
                    .add( "Arcateen V" )
                    .add( "Archetryx" )
                    .add( "Arden" )
                    .add( "Argolis" )
                    .add( "Argos" )
                    .add( "Aridius" )
                    .add( "Arkannis Major" )
                    .add( "Arkheon" )
                    .add( "Artaris" )
                    .add( "Asgard" )
                    .add( "Astra" )
                    .add( "Atrios" )
                    .add( "Augea " )
                    .add( "Auros" )
                    .add( "Avalon" )
                    .add( "Axista Four" )
                    .add( "Azure" )
                    .add( "Balhoon" )
                    .add( "Bandraginus 5" )
                    .add( "Bandril" )
                    .add( "Bane World" )
                    .add( "Barcelona" )
                    .add( "Bel" )
                    .add( "Belannia II" )
                    .add( "Belannia IV" )
                    .add( "Belepheron" )
                    .add( "Bellaphores" )
                    .add( "Bessan" )
                    .add( "Beta Two" )
                    .add( "Betelgeuse" )
                    .add( "Betrushia" )
                    .add( "Bi" )
                    .add( "Blenhorm Ogin" )
                    .add( "Blestinu" )
                    .add( "Blini-Gaar" )
                    .add( "Bliss" )
                    .add( "Bonarcha Anarda" )
                    .add( "Boromeo" )
                    .add( "Bortresoye" )
                    .add( "Bruydac" )
                    .add( "Brus" )
                    .add( "Bouken" )
                    .add( "Calliopticon" )
                    .add( "Calufrax" )
                    .add( "Calufrax Minor" )
                    .add( "Carsus" )
                    .add( "Cassius" )
                    .add( "Castor 36" )
                    .add( "Castrovalva" )
                    .add( "Catastrophea" )
                    .add( "Catrigan Nova" )
                    .add( "Centauri Seven" )
                    .add( "Cep Cassalon" )
                    .add( "Chavic Five" )
                    .add( "Cheem" )
                    .add( "Cheetah Planet" )
                    .add( "Chelonia" )
                    .add( "Chimeria" )
                    .add( "Chimera IV" )
                    .add( "Chloris" )
                    .add( "Chronos" )
                    .add( "Cinethon" )
                    .add( "Clom" )
                    .add( "Colano Alpha" )
                    .add( "Collactin" )
                    .add( "Cotter Palluni's World" )
                    .add( "Crafe Tec Heydra" )
                    .add( "Crespallion" )
                    .add( "Crestus" )
                    .add( "Crinoth" )
                    .add( "Cyrennis Minima" )
                    .add( "Daemos" )
                    .add( "Dar" )
                    .add( "Darkheart" )
                    .add( "Darp" )
                    .add( "Darillium" )
                    .add( "Delphon" )
                    .add( "Delta Magna'" )
                    .add( "Desperus" )
                    .add( "Deva Loka" )
                    .add( "Dhakan" )
                    .add( "Diadem" )
                    .add( "Dido" )
                    .add( "Dioscuros" )
                    .add( "Diplos" )
                    .add( "Discurus" )
                    .add( "Draconia" )
                    .add( "Dramos" )
                    .add( "Drahva" )
                    .add( "Dravidia" )
                    .add( "Dronid" )
                    .add( "Duchamp 331" )
                    .add( "Dulkis" )
                    .add( "Earth" )
                    .add( "Eden" )
                    .add( "Ephte Major" )
                    .add( "Enlandia" )
                    .add( "Epsilon Four Zero Gamma" )
                    .add( "Esto" )
                    .add( "Eudamus" )
                    .add( "Exarius" )
                    .add( "Exxilon" )
                    .add( "Eye of Orion" )
                    .add( "Fagiros" )
                    .add( "Felspoon" )
                    .add( "The Fifth Planet" )
                    .add( "Fisar" )
                    .add( "Flane" )
                    .add( "Florana" )
                    .add( "Freytus" )
                    .add( "Frontios" )
                    .add( "Galaxis Bright" )
                    .add( "Gallifrey" )
                    .add( "Galsec Seven" )
                    .add( "Gameworld Gamma" )
                    .add( "Gauda Prime" )
                    .add( "Gidu" )
                    .add( "Glasson Minor" )
                    .add( "Golo" )
                    .add( "Gond Homeworld" )
                    .add( "Gotta Floco" )
                    .add( "Grajick Major" )
                    .add( "Granados" )
                    .add( "Gratt" )
                    .add( "Griffoth" )
                    .add( "Griophos" )
                    .add( "Grold Homeworld" )
                    .add( "Grolon" )
                    .add( "Grundle" )
                    .add( "Hakol (aka. Harkol)" )
                    .add( "Halcya" )
                    .add( "Halergan Three" )
                    .add( "Hastus Minor" )
                    .add( "Heaven" )
                    .add( "Hedron" )
                    .add( "Heiradi" )
                    .add( "Hell" )
                    .add( "Hermethica" )
                    .add( "Hurala" )
                    .add( "Hyspero" )
                    .add( "Hydropellica Hydroxi" )
                    .add( "Indigo 3" )
                    .add( "Inter Minor" )
                    .add( "Iphitus" )
                    .add( "Jaconda" )
                    .add( "Jahoo" )
                    .add( "Jalian 17" )
                    .add( "Jan Francis IX" )
                    .add( "Junk" )
                    .add( "Jupiter" )
                    .add( "Justicia" )
                    .add( "Kalakiki" )
                    .add( "Kalaya" )
                    .add( "Kaldor" )
                    .add( "Kantra" )
                    .add( "Kanval" )
                    .add( "Kapteyn 5" )
                    .add( "Kar-Charrat" )
                    .add( "Karfel" )
                    .add( "Karn" )
                    .add( "Karas don Kazra don Slava" )
                    .add( "Karris" )
                    .add( "Kas" )
                    .add( "Kastopheria" )
                    .add( "Kastria" )
                    .add( "Katakiki" )
                    .add( "Katuria" )
                    .add( "Kegron Pluva" )
                    .add( "Kem" )
                    .add( "Kinjana" )
                    .add( "Kirith" )
                    .add( "Klechton" )
                    .add( "Kolkokron" )
                    .add( "Kosnax" )
                    .add( "Kreme" )
                    .add( "Krillia" )
                    .add( "Krontep" )
                    .add( "Krop Tor" )
                    .add( "Kurhan" )
                    .add( "Kylos" )
                    .add( "Kyrol" )
                    .add( "Lakertya" )
                    .add( "Laylora" )
                    .add( "Leela's World" )
                    .add( "Lelex" )
                    .add( "Leophantos" )
                    .add( "Levithia" )
                    .add( "The Li" )
                    .add( "Limus 4" )
                    .add( "Livonia" )
                    .add( "Loam" )
                    .add( "Lo" )
                    .add( "Logopolis" )
                    .add( "Lonsis" )
                    .add( "Lowitelom" )
                    .add( "Lucifer" )
                    .add( "Lurma" )
                    .add( "Lvan (aka. Luan)" )
                    .add( "Magellan" )
                    .add( "Magla" )
                    .add( "Magnus" )
                    .add( "Malcassairo" )
                    .add( "Manussa" )
                    .add( "Marinus" )
                    .add( "Marpesia" )
                    .add( "Mars" )
                    .add( "Mechanus" )
                    .add( "Melagophon" )
                    .add( "Melissa Majoria" )
                    .add( "Mer" )
                    .add( "Mesmerus" )
                    .add( "Messaline" )
                    .add( "Metallurgis 5" )
                    .add( "Meta Sigmafolio" )
                    .add( "Meta Vorka 6" )
                    .add( "Mete" )
                    .add( "Metralu" )
                    .add( "Miasimia Goria" )
                    .add( "Midnight" )
                    .add( "Minyos" )
                    .add( "Mira" )
                    .add( "Mira" )
                    .add( "Mo" )
                    .add( "Mogar" )
                    .add( "Mondaran" )
                    .add( "Mondas" )
                    .add( "Morestra" )
                    .add( "Morok" )
                    .add( "Museum of the Last Ones" )
                    .add( "Muscolane" )
                    .add( "Myarr" )
                    .add( "Navaros" )
                    .add( "Necros" )
                    .add( "Nefrin" )
                    .add( "Neogorgon" )
                    .add( "New Alexandria" )
                    .add( "New Earth" )
                    .add( "New Savannah" )
                    .add( "New Venus" )
                    .add( "Nooma" )
                    .add( "Nyrruh 4" )
                    .add( "Oberon" )
                    .add( "Oblivion" )
                    .add( "Ockora" )
                    .add( "Ogros" )
                    .add( "Olympus" )
                    .add( "Omphalos" )
                    .add( "One" )
                    .add( "Oseidon" )
                    .add( "Oskerion" )
                    .add( "Othrys" )
                    .add( "Overod" )
                    .add( "Padrivole Regency 9" )
                    .add( "Pandatorea" )
                    .add( "Parakon" )
                    .add( "Paradost" )
                    .add( "Peladon" )
                    .add( "Pen Haxico 2" )
                    .add( "Peri" )
                    .add( "Phaester Osiris" )
                    .add( "Pheros" )
                    .add( "Phryxus" )
                    .add( "Pictos" )
                    .add( "Planet 1" )
                    .add( "Pluto" )
                    .add( "Polymos" )
                    .add( "Polongus" )
                    .add( "Poosh" )
                    .add( "Ponton" )
                    .add( "Posikar" )
                    .add( "Proamon" )
                    .add( "Proxima Centauri" )
                    .add( "Pyro Shika" )
                    .add( "Pyrovilia" )
                    .add( "Qualactin" )
                    .add( "Quinnis" )
                    .add( "Raaga" )
                    .add( "Rago Rago Five Six Rago" )
                    .add( "Ralafea" )
                    .add( "Ranx" )
                    .add( "Ravolox" )
                    .add( "Raxacoricofallapatorius" )
                    .add( "Re" )
                    .add( "Red Rocket Rising" )
                    .add( "Red Sky Lost" )
                    .add( "Refusis II" )
                    .add( "Reja Magnum" )
                    .add( "Rex Vox Jax" )
                    .add( "Rexel 4" )
                    .add( "Ri" )
                    .add( "Riftan Five" )
                    .add( "Rigel Beta 5" )
                    .add( "Rit" )
                    .add( "Ruta 3" )
                    .add( "Ruta Magnum" )
                    .add( "Ry'leh" )
                    .add( "S14" )
                    .add( "Salarius" )
                    .add( "Salostophus" )
                    .add( "Salvak" )
                    .add( "San Helios" )
                    .add( "San Kaloon" )
                    .add( "Santiny" )
                    .add( "Sant's World" )
                    .add( "Sarn" )
                    .add( "Saturnyne" )
                    .add( "Sava" )
                    .add( "Scalpor" )
                    .add( "Scrantek" )
                    .add( "Scotia" )
                    .add( "Segonax" )
                    .add( "Sense-Sphere" )
                    .add( "Shada" )
                    .add( "Shadmoch" )
                    .add( "Shallacatop" )
                    .add( "Shan Shen" )
                    .add( "Shantella Prime" )
                    .add( "Sigma" )
                    .add( "Siralos" )
                    .add( "Sireen" )
                    .add( "Sirius IV" )
                    .add( "Sirius V" )
                    .add( "Skaar" )
                    .add( "Skaro" )
                    .add( "Skonnos" )
                    .add( "Skythros" )
                    .add( "The Slough" )
                    .add( "Solos" )
                    .add( "Sontar" )
                    .add( "Spiridon" )
                    .add( "Splendurosa" )
                    .add( "Starfall" )
                    .add( "Stella Stora" )
                    .add( "Sto" )
                    .add( "Strepto" )
                    .add( "Stricium" )
                    .add( "Sunday" )
                    .add( "Svartos" )
                    .add( "Sycorax" )
                    .add( "Sylvaniar" )
                    .add( "Sza" )
                    .add( "Ta" )
                    .add( "Tara" )
                    .add( "Tarsius" )
                    .add( "Taurean Nomeworld" )
                    .add( "Telos" )
                    .add( "Tenten 10" )
                    .add( "Terileptus" )
                    .add( "Terra Alpha" )
                    .add( "Terra Beta" )
                    .add( "Terradon" )
                    .add( "Tersurus" )
                    .add( "Tetrapyriar" )
                    .add( "Thegeros" )
                    .add( "Thera" )
                    .add( "Therka" )
                    .add( "Therra" )
                    .add( "Thordon" )
                    .add( "Thoros Alpha" )
                    .add( "Thrace" )
                    .add( "Thuron" )
                    .add( "Tiermann's World" )
                    .add( "Tigella" )
                    .add( "Tigus" )
                    .add( "Tisar" )
                    .add( "Titan" )
                    .add( "Titan 3" )
                    .add( "Titania" )
                    .add( "Tokl" )
                    .add( "Toop" )
                    .add( "Torajii Alpha" )
                    .add( "Traken" )
                    .add( "Trieste" )
                    .add( "Tranquela" )
                    .add( "Trion" )
                    .add( "Triton" )
                    .add( "Tythonus" )
                    .add( "Um" )
                    .add( "Unicepter IV" )
                    .add( "Uranus" )
                    .add( "Ur" )
                    .add( "Usurius" )
                    .add( "Utopia" )
                    .add( "UX-4732" )
                    .add( "Uxarieus" )
                    .add( "Vampire Planet" )
                    .add( "Vandos" )
                    .add( "Varos" )
                    .add( "Vardon" )
                    .add( "Varnicon" )
                    .add( "Vasilip" )
                    .add( "Vel Consadine" )
                    .add( "Venessia" )
                    .add( "Venus" )
                    .add( "Verd" )
                    .add( "Verticulus" )
                    .add( "Veturia" )
                    .add( "Vij" )
                    .add( "Viperon" )
                    .add( "Vita 15" )
                    .add( "Voga" )
                    .add( "Volag-Noc" )
                    .add( "Vollotha" )
                    .add( "Voracia" )
                    .add( "Vortis" )
                    .add( "Vulcan" )
                    .add( "Vulpana" )
                    .add( "Wilson 1" )
                    .add( "Woldyhool" )
                    .add( "Woman Wept" )
                    .add( "Xenon" )
                    .add( "Xeros" )
                    .add( "Xeriphas" )
                    .add( "Yegros Alpha" )
                    .add( "Zaakros" )
                    .add( "Zamper" )
                    .add( "Zanak" )
                    .add( "Zazz" )
                    .add( "Zeen 4" )
                    .add( "Zeos" )
                    .add( "Zephon" )
                    .add( "Zeta Major" )
                    .add( "Zeta Minor" )
                    .add( "Zil" )
                    .add( "Zolfa Thura" )
                    .add( "Zom" )
                    .add( "Zygor" )
                    .commit( db );

            tx.success();
        }
    }
}
